[package]
name = "envelope"
version = "0.3.9"
edition = "2021"
authors = ["Mattia Righetti <matt95.righetti@gmail.com>"]
repository = "https://github.com/mattrighetti/envelope"
readme = "README.md"

[dependencies]
clap = { version = "4", features = ["derive"] }
prettytable-rs = "0.10.0"
tokio = { version = "1", features = ["macros", "rt"] }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio"] }
sea-query = "0"
sea-query-binder = { version = "0", features = [ "sqlx-sqlite", "with-uuid" ] }
