[package]
name = "envelope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }

[dependencies.sqlx]
version = "0.7.1"
features = [
  "runtime-tokio-rustls",
  "time",
  "sqlite",
  "uuid",
]
